---

- hosts: db
  gather_facts: no  # facts 수집 x ->> anp facts3.yml 하면 오류남
  tasks:
  - name: Manually gather facts
    ansible.builtin.setup:  # fqdn, ipv4.address의 facts 수집
     
  - name: Print all facts
    ansible.builtin.debug:
      msg: >
        The default IPv4 address of {{ ansible_facts.fqdn }}
        is {{ ansible_facts.default_ipv4.address }}